apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: lumen-maturity-analysis
spec:
  args:
    - name: promServer
    - name: threshold
      value: "0.5"
  metrics:
    - name: mscore-pass
      interval: 30s
      successCondition: result[0] >= {{args.threshold}}
      provider:
        prometheus:
          address: {{args.promServer}}
          query: |
            avg_over_time(lumen_m_score[2m])
