{{- if and .Values.gate.enabled .Values.gate.hooks.pre }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "lumen.fullname" . }}-pre-gate
  labels:
    {{- include "lumen.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      labels:
        {{- include "lumen.labels" . | nindent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: gate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ROI_ENV
              value: {{ .Values.gate.roi.env | quote }}
            - name: ROI_SERVICE
              value: {{ .Values.gate.roi.service | quote }}
            - name: MATURITY_OVERALL_MIN
              value: {{ .Values.gate.maturity.overallMin | quote }}
            - name: MATURITY_SENSE_MIN
              value: {{ .Values.gate.maturity.senseMin | quote }}
            - name: MATURITY_FEEDBACK_MIN
              value: {{ .Values.gate.maturity.feedbackMin | quote }}
            - name: MATURITY_RELEASE_MIN
              value: {{ .Values.gate.maturity.releaseMin | quote }}
            - name: MATURITY_PENALTY
              value: {{ .Values.gate.maturity.penalty | quote }}
            - name: FLIP_PLATFORM
              value: {{ .Values.gate.flipback.platform | quote }}
            - name: FLIP_TARGET
              value: {{ .Values.gate.flipback.target | quote }}
          command: ["bash","-lc"]
          args:
            - |
              set -euo pipefail
              echo "[pre-gate] running integrated gate (ROI/SLO × Maturity)"
              python scripts/integrated_gate_v19_v15.py || FAIL=$? || true
              if [[ "${FAIL:-0}" != "0" ]]; then
                echo "[pre-gate] FAIL — status code $FAIL"
                if [[ "$FLIP_PLATFORM" == "helm" ]]; then
                  echo "[pre-gate] attempting HELM rollback to $FLIP_TARGET"
                  TARGET="$FLIP_TARGET" RELEASE="${ROI_SERVICE}" bash scripts/helm_rollback_v19.sh || true
                elif [[ "$FLIP_PLATFORM" == "argocd" ]]; then
                  echo "[pre-gate] attempting ARGOCD rollback to $FLIP_TARGET"
                  APP="${ROI_SERVICE}" REVISION="$FLIP_TARGET" bash scripts/argocd_rollback_v19.sh || true
                fi
                exit $FAIL
              fi
              echo "[pre-gate] PASS"
{{- end }}
