apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "lumen.fullname" . }}-kafka-topics
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: topic-init
          image: bitnami/kafka:3.7
          command: ["/bin/bash","-lc"]
          args:
            - >
              kafka-topics.sh --bootstrap-server {{ .Values.streaming.kafka.bootstrap }}
              --create --if-not-exists --topic {{ .Values.streaming.kafka.topicResInput }} --replication-factor 1 --partitions 3 &&
              echo "topics ensured";
