name: lumen_v19_full_ops_loop
on:
  schedule:
    - cron: "*/30 * * * *"  # every 30 minutes
  workflow_dispatch:
    inputs:
      roi_env:
        description: "env (prod/stage/dev) for ROI gate"
        default: "prod"
jobs:
  loop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Start exporters (best-effort)
        run: |
          (cd lumen_v1_8_assets && (python roi_risk_exporter_v18.py &) && sleep 1) || true
          (cd lumen_v1_9_assets && (python prod_roi_exporter_v19.py &) && sleep 1) || true
      - name: Readiness check
        run: |
          python scripts/ops_readiness_check_v2.py
      - name: ROI gate + Incident bridge + Notifications
        env:
          ROI_ENV: ${{ github.event.inputs.roi_env || 'prod' }}
          ROI_THRESHOLDS_FILE: docs/roi_thresholds_v19.example.yaml
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python scripts/roi_incident_bridge_v19.py || true
      - name: Upload loop artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lumen-v19-full-ops-loop
          path: |
            docs/OPS_READINESS_REPORT_v2.md
            docs/OPS_READINESS_SUMMARY_v2.json
