name: lumen_ops_readiness_v2
on:
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: "30 2 * * *"
jobs:
  readiness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Generate readiness report
        run: |
          python scripts/ops_readiness_check_v2.py
      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: ops-readiness-v2
          path: |
            docs/OPS_READINESS_REPORT_v2.md
            docs/OPS_READINESS_SUMMARY_v2.json
