name: lumen_helm_unittest
on:
  pull_request:
    paths:
      - 'charts/lumen/**'
  workflow_dispatch: {}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4
      - name: Install helm-unittest plugin
        run: |
          helm plugin install https://github.com/helm-unittest/helm-unittest.git
      - name: Run helm unittest
        working-directory: charts/lumen
        run: |
          helm unittest -f tests/*.yaml .
