name: lumen_v19_composite_gate_and_rollback
on:
  workflow_dispatch:
    inputs:
      roi_env:
        description: "Environment"
        default: "prod"
      roi_service:
        description: "Service"
        default: "api"
      platform:
        description: "rollback platform (none|helm|argocd)"
        default: "none"
      target:
        description: "target revision (helm TARGET / argo REVISION)"
        default: "previous"
jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Start exporters (best-effort)
        run: |
          (cd lumen_v1_9_assets && (python prod_roi_exporter_v19.py &) && sleep 1) || true
          (cd lumen_v1_9_assets && (python slo_exporter_v19.py &) && sleep 1) || true
      - name: Composite gate
        id: gate
        env:
          ROI_ENV: ${{ github.event.inputs.roi_env }}
          ROI_SERVICE: ${{ github.event.inputs.roi_service }}
          ROI_THRESHOLDS_MATRIX_FILE: docs/roi_thresholds_matrix_v19.example.yaml
        run: |
          set +e
          OUT=$(python scripts/composite_roi_v19.py); CODE=$?
          echo "$OUT"
          echo "json<<EOF" >> $GITHUB_OUTPUT
          echo "$OUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          exit $CODE
  rollback:
    needs: eval
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Helm rollback (optional)
        if: ${{ github.event.inputs.platform == 'helm' }}
        env:
          NAMESPACE: default
          RELEASE: ${{ github.event.inputs.roi_service }}
          TARGET: ${{ github.event.inputs.target }}
        run: |
          bash scripts/helm_rollback_v19.sh
      - name: ArgoCD rollback (optional)
        if: ${{ github.event.inputs.platform == 'argocd' }}
        env:
          APP: ${{ github.event.inputs.roi_service }}
          REVISION: ${{ github.event.inputs.target }}
        run: |
          bash scripts/argocd_rollback_v19.sh
