name: lumen_v18_adaptive_weekly
on:
  schedule:
    - cron: "0 3 * * 1"   # every Monday 03:00 UTC
  workflow_dispatch: {}
jobs:
  adaptive-weekly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Derive adaptive policy
        working-directory: lumen_v1_8_assets
        run: |
          python ledger_analyzer_v18.py
          (python policy_trace_exporter_v18.py &) && sleep 1
          curl -fsSL http://127.0.0.1:9154/metrics | head -n 20
      - name: Start v1.6 + v1.7 indices
        run: |
          (cd lumen_v1_6_assets && (python stream_enricher_v1.py < samples.jsonl &) && sleep 1 && (python metrics_enrichment_exporter.py &) && sleep 1 && (python resonance_adapter_v1_native_matrix.py &) && sleep 2 && (python adaptation_metrics_exporter.py &) && sleep 1)
          (cd lumen_v1_7_assets && (python metrics_feedback_graph_exporter.py &) && sleep 1)
      - name: Gate with latest policy
        id: gate
        working-directory: lumen_v1_8_assets
        continue-on-error: true
        run: |
          python v18_gate_runner.py --metrics http://127.0.0.1:9153/metrics
      - name: Rollback on failure
        if: steps.gate.outcome == 'failure'
        working-directory: lumen_v1_7_assets
        run: |
          python v17_gate_rollback.py --state-file ../lumen_v1_6_assets/adaptation_state.json --window 1200 --alpha 0.12
          exit 2
      - name: Ledger ingest
        if: steps.gate.outcome == 'success'
        working-directory: lumen_v1_7_assets
        run: |
          python ledger_v17_ingestor.py
          ls -lh ledger_v17.db
