name: lumen_v19_flipback_notify
on:
  workflow_run:
    workflows: ["lumen_v19_composite_score_and_flipback"]
    types: [completed]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Send summary notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python scripts/incident_notifier_v19.py --title "Flipback workflow completed" --text "See artifacts for composite score and flipback decision." --level green
