name: lumen_v15_release_publish
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag (e.g. v1.5-rc)'
        required: true
      prerelease:
        description: 'Mark as pre-release (true/false)'
        default: 'true'
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Read release notes
        id: notes
        run: |
          echo "notes<<EOF" >> $GITHUB_OUTPUT
          cat docs/RELEASE_NOTES_v1_4_to_v1_5.md >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: "Lumen ${{ github.event.inputs.tag }}"
          body: ${{ steps.notes.outputs.notes }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease }}
