name: lumen_v18_rc_pipeline
on:
  workflow_dispatch: {}
jobs:
  v18-rc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Derive adaptive policy
        working-directory: lumen_v1_8_assets
        run: |
          python ledger_analyzer_v18.py
          cat adaptive_gate_policy_v18.json
      - name: Start v1.6 stack (native matrix)
        working-directory: lumen_v1_6_assets
        run: |
          (python stream_enricher_v1.py < samples.jsonl &) && sleep 1
          (python metrics_enrichment_exporter.py &) && sleep 1
          (python resonance_adapter_v1_native_matrix.py &) && sleep 2
          (python adaptation_metrics_exporter.py &) && sleep 1
      - name: Build v1.7 graph + exporter
        working-directory: lumen_v1_7_assets
        run: |
          python feedback_graph_core_v17.py
          (python metrics_feedback_graph_exporter.py &) && sleep 1
          curl -fsSL http://127.0.0.1:9153/metrics | head -n 20
      - name: Adaptive Gate
        id: gate
        working-directory: lumen_v1_8_assets
        continue-on-error: true
        run: |
          python v18_gate_runner.py --metrics http://127.0.0.1:9153/metrics
      - name: Rollback on failure
        if: steps.gate.outcome == 'failure'
        working-directory: lumen_v1_7_assets
        run: |
          python v17_gate_rollback.py --state-file ../lumen_v1_6_assets/adaptation_state.json --window 1200 --alpha 0.12
          exit 2
      - name: Ledger ingest
        if: steps.gate.outcome == 'success'
        working-directory: lumen_v1_7_assets
        run: |
          python ledger_v17_ingestor.py
          ls -lh ledger_v17.db
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lumen-v18-rc
          path: |
            lumen_v1_8_assets/adaptive_gate_policy_v18.json
            lumen_v1_7_assets/feedback_graph.json
            lumen_v1_7_assets/gain_alpha_matrix.json
            lumen_v1_7_assets/indices.json
            lumen_v1_7_assets/ledger_v17.db
