name: lumen_v15_maturity_gate_and_hint
on:
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: "20 3 * * *"
  workflow_dispatch: {}
jobs:
  maturity:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Compute spectrum
        run: |
          python lumen_v1_5_preview_assets/maturity_spectrum_v15_alpha.py || true
          python lumen_v1_5_preview_assets/maturity_spectrum_window_v15.py || true
      - name: Gate on maturity
        id: gate
        env:
          MATURITY_OVERALL_MIN: "0.60"
          MATURITY_SENSE_MIN: "0.50"
          MATURITY_FEEDBACK_MIN: "0.50"
          MATURITY_RELEASE_MIN: "0.50"
        run: |
          set +e
          OUT=$(python scripts/maturity_gate_v15.py); CODE=$?
          echo "$OUT"
          echo "json<<EOF" >> $GITHUB_OUTPUT
          echo "$OUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          exit $CODE
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const j = JSON.parse(process.env.GATE_JSON || '{}');
            const status = j.status || 'UNKNOWN';
            const m = j.maturity || {}; const thr = j.thresholds || {};
            const body = [
              '### Lumen v1.5 — Maturity Gate',
              '',
              `**Status:** ${status === 'PASS' ? '✅ PASS' : '❌ FAIL'}`,
              '',
              '| metric | value | min |',
              '|---|---:|---:|',
              `| overall | ${m.overall ?? '-'} | ${thr.overall ?? '-'} |`,
              `| sense | ${m.sense ?? '-'} | ${thr.sense ?? '-'} |`,
              `| feedback | ${m.feedback ?? '-'} | ${thr.feedback ?? '-'} |`,
              `| release | ${m.release ?? '-'} | ${thr.release ?? '-'} |`
            ].join('\n');
            await github.rest.issues.createComment({ owner: context.repo.owner, repo: context.repo.repo, issue_number: context.payload.pull_request.number, body });
        env:
          GATE_JSON: ${{ steps.gate.outputs.json }}
      - name: Apply maturity→policy hint
        if: always()
        run: |
          python scripts/maturity_to_policy_hint_v15.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: maturity-spectrum-v15
          path: |
            lumen_v1_5_preview_assets/Maturity_Spectrum_v1_5_alpha.json
            docs/V15_MATURITY_SPECTRUM.md
            metrics/maturity_spectrum.prom
            metrics/maturity_spectrum_windows.prom
