# argocd/apps/children/lumen-monitoring.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lumen-monitoring
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<org>/<repo>.git    # TODO: set your repo
    targetRevision: main
    path: argocd/kustomize/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
