name: lumen_v17_smoke
on:
  workflow_dispatch: {}
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Build feedback graph
        working-directory: lumen_v1_7_assets
        run: |
          python feedback_graph_core_v17.py
          ls -l feedback_graph.json gain_alpha_matrix.json indices.json
      - name: Start exporter and assert metrics
        working-directory: lumen_v1_7_assets
        run: |
          (python metrics_feedback_graph_exporter.py &) && sleep 1
          curl -fsSL http://127.0.0.1:9153/metrics | grep -q lumen_v17_s_index
          curl -fsSL http://127.0.0.1:9153/metrics | head -n 20
