name: lumen_v15_build_and_release
on:
  push:
    branches: [ main ]
    paths:
      - 'lumen_v1_5_preview_assets/**'
      - 'scripts/**'
      - 'docs/**'
      - 'Dockerfile'
      - 'helm/lumen-v15-preview/**'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag (e.g., v1.5-rc, sha)'
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Derive tags
        id: meta
        run: |
          TAG="${{ github.event.inputs.tag || '' }}"
          if [ -z "$TAG" ]; then
            TAG="sha-${GITHUB_SHA::7}"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/lumen:${{ steps.meta.outputs.tag }}
  chart:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Package Helm chart
        run: |
          mkdir -p dist
          helm lint helm/lumen-v15-preview || true
          helm package helm/lumen-v15-preview --destination dist
      - name: Upload chart artifact
        uses: actions/upload-artifact@v4
        with:
          name: lumen-v15-preview-chart
          path: dist/*.tgz
