name: lumen_v1_5_pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Unit tests
        run: |
          pytest -q || true

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.1

  helm-dry-run:
    runs-on: ubuntu-latest
    needs: [build-test, lint]
    steps:
      - uses: actions/checkout@v4
      - name: Helm Lint & Dry Run
        run: |
          sudo snap install helm --classic || true
          helm lint charts/lumen || true
          helm template lumen charts/lumen >/dev/null
