name: lumen_v16_smoke
on:
  workflow_dispatch: {}

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run P1/P2/P3 smoke
        working-directory: lumen_v1_6_assets
        run: |
          python -m pip install --upgrade pip
          (python stream_enricher_v1.py < samples.jsonl &) && sleep 1
          (python metrics_enrichment_exporter.py &) && sleep 1
          (python resonance_adapter_v1.py &) && sleep 2
          (python adaptation_metrics_exporter.py &) && sleep 1
          curl -fsSL http://127.0.0.1:9151/metrics | head -n 20
          curl -fsSL http://127.0.0.1:9152/metrics | head -n 20
          python resonance_memory_store.py
          python history_tracker_v1.py
      - name: Assert metrics presence
        run: |
          curl -fsSL http://127.0.0.1:9151/metrics | grep -q lumen_enrichment_semantic_density
          curl -fsSL http://127.0.0.1:9152/metrics | grep -q lumen_window_ms
