# argocd/apps/children/lumen-v15-preview.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lumen-v15-preview
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<org>/<repo>.git    # TODO: set your repo
    targetRevision: main
    path: helm/lumen-v15-preview
    helm:
      values: |
        image:
          repository: ghcr.io/<org>/lumen
          tag: v1.5-rc
        exporter:
          enabled: true
          port: 9158
        ingestor:
          enabled: true
          kafka:
            enabled: true
            brokers: "kafka:9092"
            topic: "lumen.fractal.events"
            group: "lumen-v1-5"
          loki:
            enabled: false
        gate:
          enabled: true
          roi:
            env: "prod"
            service: "api"
          maturity:
            overallMin: 0.60
            senseMin: 0.45
            feedbackMin: 0.45
            releaseMin: 0.45
            penalty: 0.10
          flipback:
            platform: "none"
            target: "previous"
          hooks:
            pre: true
            post: true
  destination:
    server: https://kubernetes.default.svc
    namespace: lumen
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
