apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lumen.fullname" . }}-oauth2-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "lumen.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: oauth2-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "lumen.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.5.1
          args:
            - --provider={{ .Values.oauth2.provider | default "github" }}
            - --http-address=0.0.0.0:4180
            - --upstream=file:///dev/null
            - --cookie-secure=true
            - --cookie-secret=$(COOKIE_SECRET)
            - --cookie-domain={{ .Values.ingress.host | default "lumen.local" }}
            - --cookie-expire=168h
            - --email-domain=*
            - --oidc-issuer-url={{ .Values.oauth2.issuerUrl | default "" }}
            - --client-id={{ .Values.oauth2.clientID | default "" }}
            - --client-secret=$(CLIENT_SECRET)
            - --redirect-url=https://{{ .Values.ingress.host | default "lumen.local" }}/oauth2/callback
          env:
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "lumen.fullname" . }}-oauth2-secret
                  key: clientSecret
            - name: COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "lumen.fullname" . }}-oauth2-secret
                  key: cookieSecret
          ports:
            - name: http
              containerPort: 4180
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lumen.fullname" . }}-oauth2-proxy
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "lumen.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: oauth2-proxy
  ports:
    - name: http
      port: 80
      targetPort: 4180
