apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "lumen.fullname" . }}-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "lumen.fullname" . }}-rb
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: {{ include "lumen.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
