{{- if and .Values.serviceMonitor.enabled .Values.exporter.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "lumen.fullname" . }}-exporter
  namespace: {{ default .Release.Namespace .Values.serviceMonitor.namespace }}
  labels: {{- include "lumen.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "lumen.fullname" . }}
  endpoints:
    - port: http
      interval: 15s
{{- end }}
