apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.tenant.name | default "lumen-prod" }}
  labels:
    lumen/tenant: "true"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: {{ .Values.tenant.name | default "lumen-prod" }}-rq
  namespace: {{ .Values.tenant.name | default "lumen-prod" }}
spec:
  hard:
    pods: "50"
    requests.cpu: "10"
    requests.memory: "32Gi"
    limits.cpu: "20"
    limits.memory: "64Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: {{ .Values.tenant.name | default "lumen-prod" }}-lr
  namespace: {{ .Values.tenant.name | default "lumen-prod" }}
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "250m"
        memory: "512Mi"
      default:
        cpu: "1000m"
        memory: "1Gi"
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
  namespace: {{ .Values.tenant.name | default "lumen-prod" }}
spec:
  podSelector: {}
  policyTypes: ["Ingress","Egress"]
