{{- if and .Values.featureFlags.enableV16Enrichment .Values.v16.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "lumen.fullname" . }}-v16-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.v16.persistence.size | default "5Gi" }}
  storageClassName: {{ .Values.v16.persistence.storageClass | default "standard" | quote }}
{{- end }}
