name: Lumen v1.2 Canary

on:
  workflow_dispatch: {}

jobs:
  canary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/adaptive_feedback/requirements.txt || true
      - name: Stage (staging) run
        run: |
          cd tools/adaptive_feedback
          bash stage_runner.sh staging || true
      - name: Canary check
        env:
          PROM_URL: ${{ secrets.PROM_URL_STAGING }}
          SERVICE: ${{ secrets.SERVICE_NAME }}
        run: |
          cd tools/adaptive_feedback
          python canary_check.py
      - name: Promotion ticket & (optional) apply
        env:
          PROM_URL: ${{ secrets.PROM_URL_STAGING }}
          SERVICE: ${{ secrets.SERVICE_NAME }}
          SAFE_APPLY: ${{ inputs.safe_apply || '0' }}
          DRY_RUN: ${{ inputs.dry_run || '1' }}
        run: |
          cd tools/adaptive_feedback
          python canary_promote.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: canary-artifacts
          path: |
            tools/adaptive_feedback/canary_report.json
            tools/adaptive_feedback/promotion_ticket.json
