
name: Release v1.2

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag to create (e.g., v1.2.0)'
        required: true
  push:
    tags:
      - 'v1.2.*'

jobs:
  build-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bundle artifacts
        run: |
          cd tools/adaptive_feedback
          python - <<'PY'
import shutil, os
os.makedirs('build', exist_ok=True)
shutil.copy('build/lumen_v1.2_artifacts.zip','build/lumen_v1.2_artifacts.zip')
shutil.copy('build/lumen_v1.2_artifacts.zip.sha256','build/lumen_v1.2_artifacts.zip.sha256')
PY
      - name: Upload bundle
        uses: actions/upload-artifact@v4
        with:
          name: lumen-v1.2-bundle
          path: tools/adaptive_feedback/build/*

  github-release:
    needs: build-package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: lumen-v1.2-bundle
          path: dist
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.tag || github.ref_name }}
          name: "Lumen v1.2.0 Final"
          body_path: tools/adaptive_feedback/RELEASE_NOTES_v1.2.0.md
          files: |
            dist/lumen_v1.2_artifacts.zip
            dist/lumen_v1.2_artifacts.zip.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
