name: security-policy-gates

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main

jobs:
  security-scans:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Gitleaks scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --redact --no-banner

      - name: Semgrep scan
        uses: semgrep/semgrep-action@v1
        with:
          config: p/ci
