name: Weekly Rollup
description: Summarize weekly highlights/decisions/metrics/incidents/actions
title: "[Weekly] YYYY-MM-DD Rollup"
labels:
  - weekly-rollup
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        장문/세부는 내부 링크로 연결하고, 이 이슈에는 하이라이트만 남겨 주세요.
        템플릿 참고: docs/WEEKLY_ROLLUP_TEMPLATE.md
  - type: textarea
    id: highlights
    attributes:
      label: Highlights (3~5줄)
      description: 지난 1주간 팀/제품 주요 성과와 이슈.
      placeholder: 하이라이트 요약...
    validations:
      required: true
  - type: textarea
    id: key_decisions
    attributes:
      label: Key Decisions
      description: 중요한 결정과 내부 근거 링크.
      placeholder: "- 결정 A — (근거 링크)\n- 결정 B — (근거 링크)"
    validations:
      required: true
  - type: textarea
    id: metrics
    attributes:
      label: Metrics Snapshot
      description: 성능/SLA/비용 등 핵심 지표 요약(대시보드 링크 포함).
      placeholder: 지표 요약 및 링크...
    validations:
      required: false
  - type: textarea
    id: incidents
    attributes:
      label: Incidents & Mitigations
      description: 주요 이슈 요약과 대응/완화 내역.
      placeholder: 인시던트 요약...
    validations:
      required: false
  - type: checkboxes
    id: actions
    attributes:
      label: Action Items
      description: 실행 항목을 선택/추가하세요.
      options:
        - label: 담당자/마감일 지정 완료 (@owner, YYYY-MM-DD)
        - label: 후속 PR/작업 이슈 생성 완료
  - type: textarea
    id: references
    attributes:
      label: References
      description: 내부 리포트/대시보드/로그 등 전체 링크 목록.
      placeholder: "- [리포트] https://...\n- [대시보드] https://..."
    validations:
      required: false
