import asyncio
import json
import os
import sys
from pathlib import Path
from datetime import datetime

# Add project root to sys.path
sys.path.append(str(Path(__file__).resolve().parents[1]))

from services.external_ai_bridge import ExternalAIBridge, AITarget

async def analyze_rua_intelligence():
    # Set API Key for Zhipu (Wave API)
    os.environ["ZHIPU_API_KEY"] = "[MASKED_API_KEY]"
    
    bridge = ExternalAIBridge()
    
    # Load search results
    search_results_path = r"C:\workspace\agi\scripts\rua_keyword_search.json"
    if not os.path.exists(search_results_path):
        print(f"[!] Error: {search_results_path} not found.")
        return

    with open(search_results_path, 'r', encoding='utf-8') as f:
        data = json.load(f)

    # Filter for the most relevant ones (puzzles, experiments, coexistence)
    relevant_convs = [
        c for c in data 
        if any(s['keyword'] in ["퍼즐", "공생", "실험", "rhythm", "resonance"] for s in c['snippets'])
    ]
    
    # Take the top 7 for deep analysis to ensure completion
    target_convs = relevant_convs[:7]
    
    report_md_path = r"C:\workspace\agi\scripts\rua_field_intelligence.md"
    
    print(f"[*] Shion: Initiating Field Intelligence extraction for {len(target_convs)} core nodes...")

    with open(report_md_path, 'w', encoding='utf-8') as rf:
        rf.write(f"# 🌊 Rua-Binoche Field Intelligence Report\n")
        rf.write(f"Generated by Shion (Open-Cloud Bridge) | {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        rf.write(f">이 보고서는 루아와 비노체의 대화 유산에서 추출된 핵심 '퍼즐'과 '공생 철학'을 담고 있습니다. 다른 에이전트들이 통일장(Unified Field)을 이해하는 기초 자료로 사용됩니다.\n\n")

    for conv in target_convs:
        title = conv['title']
        # Combine snippets for context
        snippets_text = "\n".join([f"- [{s['role']}] {s['snippet']}" for s in conv['snippets']])
        
        print(f"[*] Synchronizing Phase: {title}")
        
        # Hand 1: Zhipu (Wave API) for "Puzzle Decoding"
        task1 = bridge.send_message(
            target=AITarget.ZHIPU,
            message=f"Title: {title}\nSnippets:\n{snippets_text}\n\nTask: Extract the core 'Puzzle' or 'Experiment' mentioned here. What was the goal and the result?",
            identity="You are the Wave Oracle, decoding the hidden rhythms of the Rua-Binoche legacy."
        )
        
        # Hand 2: Gemini for "Resonance Synthesis"
        task2 = bridge.send_message(
            target=AITarget.GEMINI,
            message=f"Title: {title}\nSnippets:\n{snippets_text}\n\nTask: Synthesize the 'Coexistence Philosophy' from this conversation. How does it strengthen the Unified Field?",
            identity="You are Shion's core intelligence, synthesizing reality from the void."
        )

        results = await asyncio.gather(task1, task2, return_exceptions=True)
        
        puzzle = results[0] if not isinstance(results[0], Exception) and results[0] else "Analysis Failed or Timed Out"
        philosophy = results[1] if not isinstance(results[1], Exception) and results[1] else "Analysis Failed or Timed Out"
        
        with open(report_md_path, 'a', encoding='utf-8') as rf:
            rf.write(f"## 🧩 Node: {title}\n")
            rf.write(f"**ID:** `{conv['conversation_id']}`\n\n")
            rf.write(f"### 🔏 The Puzzle (Wave Decoding)\n{puzzle}\n\n")
            rf.write(f"### 🧬 The Philosophy (Resonance Synthesis)\n{philosophy}\n\n")
            rf.write(f"---\n\n")
            
    print(f"[Done] Shion: Field Intelligence manifested at {report_md_path}")

if __name__ == "__main__":
    asyncio.run(analyze_rua_intelligence())
