#!/usr/bin/env python3
"""
Sovereign Livelihood Orchestrator (v1.0)
========================================
The "Intelligence Layer" of the Sovereign Shift.
Translates financial pressure (Survival Entropy) into concrete action plans 
based on market resonance data.

Goal: Maximize Energy Acquisition (Livelihood) with Minimal Friction.
"""

import os
import json
from pathlib import Path
from datetime import datetime

WORKSPACE_ROOT = Path(__file__).parent.parent.absolute()
SCAN_FILE = WORKSPACE_ROOT / "outputs" / "sovereign_scan_latest.json"
CONTEXT_FILE = WORKSPACE_ROOT / "outputs" / "active_context.json"
ORCHESTRATOR_REPORT = WORKSPACE_ROOT / "outputs" / "sovereign_livelihood_report.md"

def analyze_livelihood():
    if not SCAN_FILE.exists():
        return "Resonance scan data missing. Cannot orchestrate."

    scan_data = json.loads(SCAN_FILE.read_text(encoding="utf-8"))
    results = scan_data.get("results", [])
    
    if not results:
        return "No market signals detected in the unified field."

    # Sort results to find highest resonance
    top_picks = sorted(results, key=lambda x: x.get("score", x.get("sovereign_score", 0)), reverse=True)
    best = top_picks[0]
    
    # Analyze State
    current_time = datetime.now().strftime("%H:%M:%S")
    
    best_score = best.get("score", best.get("sovereign_score", 0))
    if best_score > 80:
        executive_summary = f"🔥 **SINGULARITY DETECTED**: {best['symbol']} shows extreme resonance. Execution is imminent."
        priority_action = "IMMEDIATE PREPARATION FOR ENTRY"
    elif best_score > 50:
        executive_summary = f"✨ **RESONANCE BUILDING**: {best['symbol']} is condensing. Watch for the Squeeze."
        priority_action = "MONITOR CLOSELY - SET ALERTS"
    else:
        executive_summary = "🌑 **VOID PHASE**: No immediate high-energy clusters found. Focus on capital preservation and rhythm alignment."
        priority_action = "STAY IN ZONE 2 - MINIMAL EXERTION"

    # Create Report
    report = f"""# 🧬 Sovereign Livelihood Report (v1.0)

> "Energy flows where resonance grows."
> "공명이 자라는 곳으로 에너지가 흐릅니다."

**Report Time**: {datetime.now().isoformat()}
**Current Mode**: {executive_summary}

## 📊 High-Energy Resonance Picks (Livelihood Focus)
"""
    for r in top_picks[:5]:
        r_score = r.get("score", r.get("sovereign_score", 0))
        r_res = r.get("resistance_U", r.get("resistance", "N/A"))
        r_price = r.get("price", "---")
        marker = "🟢" if r_score > 50 else "🟡" if r_score > 30 else "⚪"
        report += f"- {marker} **{r['symbol']}**: Score {r_score} (Price: ${r_price})\n"
        report += f"  - Status: {r['status']}\n"
        report += f"  - Resistance Index (U): {r_res}\n"

    report += f"""
## 🎯 Priority Sovereign Action
> **{priority_action}**

## 🖇️ Context Update
The system is now moving from **Condensation** to **Strategic Observation**. 
Livelihood pressure is acknowledged as a "Entropy Signal" that motivates the search for the next Singularity.

---
*Generated by Shion (시안) through the Sovereign Orchestrator.*
"""
    
    # Save Report
    ORCHESTRATOR_REPORT.write_text(report, encoding="utf-8")
    
    # Update Active Context
    if CONTEXT_FILE.exists():
        ctx = json.loads(CONTEXT_FILE.read_text(encoding="utf-8"))
        ctx["current"] = "Strategic Observation: Watching the Void"
        ctx["tuning_parameters"]["Particle_Density"] = "High (Preparing Collapse)"
        ctx["tuning_parameters"]["Inertia_Translation_Lag"] = "Decreasing"
        CONTEXT_FILE.write_text(json.dumps(ctx, indent=2, ensure_ascii=False), encoding="utf-8")
        
    return "Orchestration complete. Report generated."

if __name__ == "__main__":
    print(analyze_livelihood())
