#Requires -Version 5.1
<#
.SYNOPSIS
    Update Rhythm Status with latest metrics
.DESCRIPTION
    Generates fresh rhythm status report with current system state
#>
param(
    [int]$Hours = 24,
    [switch]$OpenReport
)
. "$PSScriptRoot\Get-WorkspaceRoot.ps1"
$WorkspaceRoot = Get-WorkspaceRoot


$ErrorActionPreference = "Stop"
$WorkspaceRoot = Split-Path -Parent $PSScriptRoot

Write-Host "🎵 Updating Rhythm Status..." -ForegroundColor Cyan

# 1. Generate latest ledger summary
Write-Host "  📊 Generating ledger summary ($Hours hours)..." -ForegroundColor Gray
$pythonExe = Join-Path $WorkspaceRoot "fdo_agi_repo\.venv\Scripts\python.exe"
if (-not (Test-Path $pythonExe)) {
    $pythonExe = "python"
}

$ledgerScript = Join-Path $WorkspaceRoot "fdo_agi_repo\scripts\summarize_ledger.py"
$ledgerResult = & $pythonExe $ledgerScript --last-hours $Hours 2>&1 | Out-String

# 2. Generate monitoring report
Write-Host "  📈 Generating monitoring report..." -ForegroundColor Gray
$monitorScript = Join-Path $WorkspaceRoot "scripts\generate_monitoring_report.ps1"
& $monitorScript -Hours $Hours | Out-Null

# 3. Generate quick status
Write-Host "  ⚡ Running quick status check..." -ForegroundColor Gray
$statusScript = Join-Path $WorkspaceRoot "scripts\quick_status.ps1"
$statusResult = & $statusScript 2>&1 | Out-String

# 4. Create rhythm status snapshot
$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$rhythmFile = Join-Path $WorkspaceRoot "outputs\RHYTHM_STATUS_$timestamp.md"

$content = @"
# 🌊 Rhythm Status Snapshot

**Generated**: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
**Window**: Last $Hours hours

---

## 📊 System Metrics

``````
$statusResult
``````

---

## 🎯 AGI Activity Summary

``````
$ledgerResult
``````

---

## 💡 Insights

- Rhythm files updated every $Hours hours
- Use ``.\scripts\update_rhythm_status.ps1`` to refresh
- Dashboard: ``outputs\monitoring_dashboard_latest.html``

---

*Auto-generated by update_rhythm_status.ps1*
"@

$content | Out-File -FilePath $rhythmFile -Encoding utf8
Write-Host "✅ Rhythm status saved: $rhythmFile" -ForegroundColor Green

# Create latest symlink
$latestFile = Join-Path $WorkspaceRoot "outputs\RHYTHM_STATUS_LATEST.md"
Copy-Item $rhythmFile $latestFile -Force
Write-Host "✅ Latest status: $latestFile" -ForegroundColor Green

if ($OpenReport) {
    code $latestFile
}

Write-Host ""
Write-Host "🎉 Rhythm status updated successfully!" -ForegroundColor Green
Write-Host "   View: code outputs\RHYTHM_STATUS_LATEST.md" -ForegroundColor Cyan