# Auto Monitoring Workflow - Copilot and Comet Collaboration
# Usage: .\scripts\auto_monitoring_workflow.ps1

param(
    [switch]$SkipHealthCheck,
    [int]$TimeoutSeconds = 15
)

$ErrorActionPreference = "SilentlyContinue"
$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$base = Split-Path -Parent $scriptDir
$python = "$base\.venv\Scripts\python.exe"

if (-not (Test-Path $python)) {
    Write-Host "ERROR: Python not found at $python" -ForegroundColor Red
    exit 1
}

# Reset to catch actual errors
$ErrorActionPreference = "Continue"

Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "   Copilot and Comet Auto Workflow      " -ForegroundColor Cyan
Write-Host "========================================`n" -ForegroundColor Cyan

# Step 1: Health Check (Optional)
if (-not $SkipHealthCheck) {
    Write-Host "[1/3] Health Check..." -ForegroundColor Yellow
    
    $output = & $python "$base\scripts\send_ping.py" 2>&1 | Out-String
    
    # Extract task ID from output (format: "Task ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx")
    if ($output -match '([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})') {
        $pingTaskId = $Matches[1]
        $shortId = $pingTaskId.Substring(0, 8)
        Write-Host "   OK Ping task sent: $shortId..." -ForegroundColor Green
        
        Start-Sleep -Seconds 3
        
        $resultFile = "$base\outputs\task_queue\results\$pingTaskId.json"
        
        if (Test-Path $resultFile) {
            $result = Get-Content $resultFile | ConvertFrom-Json
            
            if ($result.status -eq "success") {
                Write-Host "   OK Comet is running (Worker: $($result.worker))" -ForegroundColor Green
            }
            else {
                Write-Host "   ERROR Comet error: $($result.error_message)" -ForegroundColor Red
                exit 1
            }
        }
        else {
            Write-Host "   WARN No response from Comet (continuing)" -ForegroundColor Yellow
        }
    }
}
else {
    Write-Host "[1/3] Health check skipped (--SkipHealthCheck)" -ForegroundColor Gray
}

# Step 2: Batch Calculation
Write-Host "`n[2/3] Running batch calculation..." -ForegroundColor Yellow

$output = & $python "$base\scripts\send_batch_calc.py" 2>&1 | Out-String

# Extract task ID from output (format: "Task ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx")
if ($output -match '([a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12})') {
    $calcTaskId = $Matches[1]
    $shortId = $calcTaskId.Substring(0, 8)
    Write-Host "   OK Calculation task sent: $shortId..." -ForegroundColor Green
    
    Write-Host "   Waiting for Comet ($TimeoutSeconds seconds)..." -ForegroundColor Cyan
    Start-Sleep -Seconds $TimeoutSeconds
    
    $resultFile = "$base\outputs\task_queue\results\$calcTaskId.json"
    
    if (Test-Path $resultFile) {
        $result = Get-Content $resultFile | ConvertFrom-Json
        
        if ($result.status -eq "success") {
            Write-Host "   OK Calculation complete!" -ForegroundColor Green
        }
        else {
            Write-Host "   WARN Calculation error: $($result.error_message)" -ForegroundColor Yellow
            Write-Host "   HINT Handler may not be implemented (see COMET_handler_guide.md)" -ForegroundColor Gray
        }
    }
    else {
        Write-Host "   WARN No result file (Comet may not have processed yet)" -ForegroundColor Yellow
    }
}

# Step 3: Generate Report
Write-Host "`n[3/3] Generating report..." -ForegroundColor Yellow

$reportPath = "$base\outputs\monitoring_auto_report.md"

$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"

$reportContent = @"
# Auto Monitoring Report

**Generated:** $timestamp

## Workflow Status

### 1. Health Check
- Status: $(if ($SkipHealthCheck) { "Skipped" } else { "Executed" })
- Ping Task ID: $(if ($pingTaskId) { $pingTaskId } else { "N/A" })
- Result: $(if ($pingTaskId -and (Test-Path "$base\outputs\task_queue\results\$pingTaskId.json")) { "Success" } else { "Pending or Failed" })

### 2. Batch Calculation
- Status: Executed
- Task ID: $(if ($calcTaskId) { $calcTaskId } else { "N/A" })
- Expected Metrics: success_rate, error_rate, avg_response, cache_hit
- Result: $(if ($calcTaskId -and (Test-Path "$base\outputs\task_queue\results\$calcTaskId.json")) { "Available" } else { "Pending" })

### 3. Next Steps

**If handlers are not implemented:**
1. Open: ``COMET_handler_guide.md``
2. Implement TypeScript handlers in Comet extension
3. Re-run this workflow

**If all tasks succeeded:**
- Review result files in ``outputs/task_queue/results/``
- Use ``fetch_and_format_result.py`` for formatted output
- Schedule this workflow with Task Scheduler

---

*This report was auto-generated by auto_monitoring_workflow.ps1*
"@

$reportContent | Out-File -FilePath $reportPath -Encoding UTF8

Write-Host "   OK Report saved: $reportPath" -ForegroundColor Green

# Summary
Write-Host "`n========================================" -ForegroundColor Cyan
Write-Host "   Workflow Complete!                   " -ForegroundColor Cyan
Write-Host "========================================`n" -ForegroundColor Cyan

Write-Host "Next actions:" -ForegroundColor White
Write-Host "  1. Review report: code $reportPath" -ForegroundColor Gray
Write-Host "  2. Check results: ls outputs\task_queue\results\" -ForegroundColor Gray
Write-Host "  3. Implement handlers: See COMET_handler_guide.md" -ForegroundColor Gray

exit 0
